In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torchvision

In [13]:
x = torch.randn(3, requires_grad = True)
x

tensor([ 0.7978, -0.9213,  0.0679], requires_grad=True)

In [14]:
y = x + 2
y

tensor([2.7978, 1.0787, 2.0679], grad_fn=<AddBackward0>)

In [15]:
z = y * y * 2
z = z.mean()
z

tensor(8.8447, grad_fn=<MeanBackward0>)

In [16]:
z.backward()
x.grad

tensor([3.7303, 1.4382, 2.7572])