In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torchvision

In [2]:
torch.empty(1)

tensor([9.0000e-39])

In [3]:
torch.empty((2,3))

tensor([[ 1.2813e-36,  5.4498e-14,  2.8878e-39],
        [ 2.0498e-19, -9.0072e+15,  1.1631e+33]])

In [4]:
torch.empty(1, dtype=torch.int64)

tensor([32370111954616435])

In [5]:
torch.empty(5, dtype=torch.float64)

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [6]:
torch.empty(2,3,3)

tensor([[[9.2755e-39, 1.0653e-38, 8.4490e-39],
         [6.9796e-39, 9.2755e-39, 1.0837e-38],
         [9.9184e-39, 9.0000e-39, 1.0561e-38]],

        [[1.0653e-38, 4.1327e-39, 8.9082e-39],
         [9.8265e-39, 9.4592e-39, 1.0561e-38],
         [1.0653e-38, 1.0469e-38, 9.5510e-39]]])

In [7]:
torch.rand(2,3,3)

tensor([[[0.9687, 0.3275, 0.4119],
         [0.8644, 0.9272, 0.1566],
         [0.7267, 0.3254, 0.6923]],

        [[0.8691, 0.2005, 0.5167],
         [0.2161, 0.2397, 0.5807],
         [0.3093, 0.9869, 0.7297]]])

In [8]:
torch.zeros(2,3,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [9]:
torch.ones(2,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [10]:
torch.empty(2,3,3).size()[0]

2

In [11]:
torch.tensor([2,3,4,5]).size()

torch.Size([4])

In [12]:
torch.empty(2,1).size()

torch.Size([2, 1])

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [14]:
# element wise addition
z = x + y 
print(z)

z = torch.add(x,y)
print(z)

tensor([[0.6772, 1.3751],
        [0.9434, 1.3778]])
tensor([[0.6772, 1.3751],
        [0.9434, 1.3778]])


In [15]:
# Inplace addition
# All functions ending with underscore will do inplace operation.
print(x,y)
y.add_(x)
print(x,y)

tensor([[0.5640, 0.7461],
        [0.2268, 0.4915]]) tensor([[0.1132, 0.6290],
        [0.7166, 0.8862]])
tensor([[0.5640, 0.7461],
        [0.2268, 0.4915]]) tensor([[0.6772, 1.3751],
        [0.9434, 1.3778]])


In [16]:
# Slicing operations
x = torch.rand(4,3)
x

tensor([[0.0093, 0.2182, 0.7056],
        [0.0895, 0.3573, 0.5722],
        [0.9575, 0.6033, 0.9902],
        [0.9358, 0.1351, 0.7038]])

In [17]:
x[2:, 1:]

tensor([[0.6033, 0.9902],
        [0.1351, 0.7038]])

In [18]:
x[2,2]

tensor(0.9902)

In [19]:
# Can only be used if the tensor has one value
x[2,2].item()

0.9901553988456726

In [20]:
y = x.view(3,4)
y

tensor([[0.0093, 0.2182, 0.7056, 0.0895],
        [0.3573, 0.5722, 0.9575, 0.6033],
        [0.9902, 0.9358, 0.1351, 0.7038]])

In [21]:
y = x.view(12)
y

tensor([0.0093, 0.2182, 0.7056, 0.0895, 0.3573, 0.5722, 0.9575, 0.6033, 0.9902,
        0.9358, 0.1351, 0.7038])

In [22]:
y = x.view(-1, 2)
y

tensor([[0.0093, 0.2182],
        [0.7056, 0.0895],
        [0.3573, 0.5722],
        [0.9575, 0.6033],
        [0.9902, 0.9358],
        [0.1351, 0.7038]])

In [23]:
a = torch.ones(5)
print(a)
print(np.array(a))
b = a.numpy()
print(b)
print(type(b))

# But we need to be careful because if the tensor is on the CPU, then both objects will share
# the same memory location. Change in one, will be reflected in the other.

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [26]:
b.add_(1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [3]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device= device)
    print(x)

tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [2]:
a=torch.cuda.FloatTensor()

In [4]:
y = x.numpy()
x.add_(1)
print(x)
print(y)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [2]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)

In [3]:
A_times_B

tensor([[0, 2],
        [0, 2]])